/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeToken } from "./FakeToken";
export type { SpaceVikingsStacking } from "./SpaceVikingsStacking";